'use client';

import { useEffect, useState } from 'react';
import { BadgePercent, Plus, Trash2 } from 'lucide-react';
import { createClient } from '@/core/supabase/client';

type Discount = { id: string; code: string; type: 'percent' | 'fixed' | 'bogo'; value: number; minimum: number; usageLimit: number; expiresAt: string; target: string; automatic: boolean; active: boolean };
const blank = (): Discount => ({ id: crypto.randomUUID(), code: '', type: 'percent', value: 10, minimum: 0, usageLimit: 100, expiresAt: '', target: 'all', automatic: false, active: true });

export default function DiscountsPage() {
  const [discounts, setDiscounts] = useState<Discount[]>([]);
  const [saved, setSaved] = useState(false);
  useEffect(() => { const timer = window.setTimeout(async () => { const { data } = await createClient().from('store_settings').select('value').eq('key','discount_rules').maybeSingle(); if (Array.isArray(data?.value)) setDiscounts(data.value as unknown as Discount[]); }, 0); return () => clearTimeout(timer); }, []);
  const update = (id: string, changes: Partial<Discount>) => setDiscounts((current) => current.map((item) => item.id === id ? {...item,...changes}:item));
  const save = async () => { const { error } = await createClient().from('store_settings').upsert({key:'discount_rules',value:discounts}); if (!error) { setSaved(true); window.setTimeout(() => setSaved(false), 2000); } };
  return <div className="space-y-5"><div className="admin-card flex flex-col sm:flex-row justify-between gap-4"><div><h2 className="display text-2xl">Промокоды и скидки</h2><p className="text-xs text-muted mt-2">Процент, фиксированная скидка, BOGO и автоматические правила.</p></div><button onClick={() => setDiscounts((current) => [blank(),...current])} className="btn btn-dark"><Plus size={16} /> Добавить</button></div>{discounts.map((discount) => <article className="admin-card" key={discount.id}><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Field label="Код" value={discount.code} change={(code) => update(discount.id,{code:code.toUpperCase()})} /><label><L>Тип</L><select className="field mt-2" value={discount.type} onChange={(e) => update(discount.id,{type:e.target.value as Discount['type']})}><option value="percent">Процент</option><option value="fixed">Фиксированная сумма</option><option value="bogo">Buy One Get One</option></select></label><Field label="Значение" type="number" value={String(discount.value)} change={(value) => update(discount.id,{value:Number(value)})} /><Field label="Минимальный заказ" type="number" value={String(discount.minimum)} change={(minimum) => update(discount.id,{minimum:Number(minimum)})} /><Field label="Лимит использований" type="number" value={String(discount.usageLimit)} change={(usageLimit) => update(discount.id,{usageLimit:Number(usageLimit)})} /><Field label="Действует до" type="date" value={discount.expiresAt} change={(expiresAt) => update(discount.id,{expiresAt})} /><Field label="Товар / коллекция / all" value={discount.target} change={(target) => update(discount.id,{target})} /><div className="flex flex-col gap-3 justify-center"><Check label="Автоматически" checked={discount.automatic} change={(automatic) => update(discount.id,{automatic})} /><Check label="Активен" checked={discount.active} change={(active) => update(discount.id,{active})} /></div></div><button onClick={() => setDiscounts((current) => current.filter((item) => item.id !== discount.id))} className="text-red-700 text-xs flex gap-2 mt-5"><Trash2 size={14} /> Удалить правило</button></article>)}{!discounts.length && <div className="admin-card text-center py-14 text-muted"><BadgePercent className="mx-auto mb-3" />Скидок пока нет.</div>}<div className="sticky bottom-4 flex justify-end"><button onClick={() => void save()} className="btn btn-dark shadow-xl">{saved ? 'Сохранено' : 'Сохранить скидки'}</button></div></div>;
}
function L({children}:{children:React.ReactNode}){return <span className="text-xs text-muted">{children}</span>}
function Field({label,value,change,type='text'}:{label:string;value:string;change:(value:string)=>void;type?:string}){return <label><L>{label}</L><input className="field mt-2" type={type} value={value} onChange={(e)=>change(e.target.value)} /></label>}
function Check({label,checked,change}:{label:string;checked:boolean;change:(value:boolean)=>void}){return <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={checked} onChange={(e)=>change(e.target.checked)} />{label}</label>}
